### ISSUE TITLE
Automated workflow to generate installable flarum packages

### ISSUE THREAD

**Issue by luceos** [flarum/framework#3561]

**Comment by luceos** [comment]
```
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  copy:
    env:
      commitmsg: ${{ github.event.head_commit.message }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Push binary to extiverse/helper
      uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'builds/extiverse'
        destination_repo: 'extiverse/helper'
        destination_branch: 'main'
        destination_folder: 'bin'
        user_email: 'Daniël Klabbers'
        user_name: 'luceos'
```

Inspiration to copy tarball from framework to flarum/flarum.
